# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "mysql2"
gem "activerecord"
gem "aws-sdk-s3"
gem "elasticsearch", "~> 6.1.0"
